### ISSUE TITLE
ModuleNotFoundError: No module named 'tests' после команды testit results import --help

### ISSUE THREAD

**Issue by lebedevadare** [testit-tms/adapters-python#139]
После ввода команды `testit results import --help` получаю ошибку 
Traceback (most recent call last):
  File "/home/darya/.local/bin/testit", line 5, in <module>
    from testit.__main__ import main
  File "/home/darya/.local/lib/python3.10/site-packages/testit/__main__.py", line 69, in <module>
    main()
  File "/home/darya/.local/lib/python3.10/site-packages/testit/__main__.py", line 30, in main
    files.append(import_module(f'tests.{file[:-3]}'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'tests'

![Screenshot from 2024-04-12 16-36-00](https://github.com/testit-tms/adapters-python/assets/45065274/caa1ee7a-fc0e-4e05-9113-883d720b7b14)

**Comment by taipoxinous** [comment]
Закрываю issue за неактуальностью. Если проблемы еще актуальны - напишите нам тут: https://testit.software/support
